name: pythondatascientist
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.10.0
  - aiohttp=3.6.3
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - audioread=2.1.9
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - blosc=1.20.1
  - branca=0.4.1
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.8
  - cachetools=4.1.1
  - cartopy=0.18.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2020.12.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - ffmpeg=4.3.1
  - folium=0.11.0
  - freetype=2.10.4
  - gast=0.4.0
  - geos=3.8.0
  - giflib=5.2.1
  - google-auth=1.22.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - imbalanced-learn=0.7.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jdcal=1.4.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.0
  - lcms2=2.11
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libflac=1.3.3
  - libiconv=1.15
  - liblapack=3.9.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - librosa=0.8.0
  - libsndfile=1.0.30
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libvorbis=1.3.7
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.35.0
  - lxml=4.6.1
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - multidict=4.7.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.3
  - networkx=2.5
  - nltk=3.5
  - notebook=6.1.5
  - numba=0.52.0
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openpyxl=3.0.5
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - owslib=0.21.0
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11.2
  - pandocfilters=1.4.3
  - parso=0.8.1
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.3
  - pooch=1.3.0
  - proj=6.2.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.13.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyepsg=0.4.0
  - pygments=2.7.3
  - pyjwt=1.7.1
  - pykdtree=1.3.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyreadr=0.3.9
  - pyrsistent=0.17.3
  - pyshp=2.1.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.4
  - pywavelets=1.1.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - regex=2020.11.13
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - resampy=0.2.2
  - rsa=4.6
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - send2trash=1.5.0
  - setuptools=51.0.0
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.15.0
  - snappy=1.1.8
  - soupsieve=2.1
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.3.0
  - termcolor=1.1.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.12.8
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.54.1
  - traitlets=5.0.5
  - urllib3=1.25.11
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.2
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
